[package]
name = "concourse-ci-test"
version = "0.1.0"
authors = ["Tom Solberg <tom.solberg@embark-studios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
