resources:
- name: concourse-ci-test
  type: git
  icon: github
  source:
    uri: https://github.com/tgolsson/concourse-ci-test

  webhook_token: concourse-ci-test-trigger

jobs:
- name: job
  public: true
  plan:
  - get: concourse-ci-test
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: docker.io/library/rust }

      run:
        path: cargo
        args: ["build"]
        dir: concourse-ci-test
