meta:
  gh-status_handlers: &gh-status-handlers
    on_success:
      put: gh-status
      inputs: [concourse-ci-test]
      params: {state: success}
    on_failure:
      put: gh-status
      inputs: [concourse-ci-test]
      params: {state: failure}
    on_error:
      put: gh-status
      inputs: [concourse-ci-test]
      params: {state: error}


resource_types:
# This manages the GitHub status lines
- name: cogito
  type: registry-image
  check_every: 1m
  source:
    repository: ((harbor.image-repo-name))/cogito
    username: ((harbor.registry-username))
    password: ((harbor.registry-password))
    tag: latest

resources:
# The repo with our Dockerfile
- name: concourse-ci-test
  type: git
  icon: github
  source:
    uri: https://github.com/tgolsson/concourse-ci-test.git
    branch: main

# Where we will push the image
- name: phatik-frontend
  type: registry-image
  icon: docker
  source:
    repository: ((phatik.image-repo-name))/frontend
    username: ((phatik.registry-username))
    password: ((phatik.registry-password))
    tag: latest

# This is the status object that will be updated in each job
- name: gh-status
  type: cogito
  check_every: 1h
  source:
    owner: tgolsson
    repo: concourse-ci-test
    access_token: ((status-token))
    context_namespace: phatik-frontend

jobs:
- name: build-and-push-docker-image
  public: true

  <<: *gh-status-handlers
  plan:
  - get: concourse-ci-test
    trigger: true

  - put: gh-status
    inputs: [concourse-ci-test]
    params: {state: pending}

  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: concourse-ci-test
      outputs:
      - name: image
      params:
        DOCKERFILE: concourse-ci-test/Dockerfiles/phatik-frontend/Dockerfile
        CONTEXT: concourse-ci-test
      run:
        path: build

  - put: phatik-frontend
    params:
      image: image/image.tar

